### ISSUE TITLE
문자열 따옴표 규율 통일

### ISSUE THREAD

**Issue by yi-hongju** [yeardream3/slackapp#4]
문자열 사용할 때 저는 보통 작은 따옴표('') 쓰는 게 더 가독성이 좋더라구요!
그래서 저희 코드는 이걸로 통일하려고 하는데 괜찮을지 의견 부탁드립니다 :)

P.S.
autopep8에는 해당 기능이 없더라구요 ㅠ... 3년 전에 이슈로 올라온 뒤로 아무 소식이 없는 듯합니다 :(

**Comment by Zyapagetti** [comment]
알겠슴다 다음 코드 작성할 때 최대한 휴먼pep8로 해보겠습니다 👍👍👍

**Comment by yi-hongju** [comment]
🦜
